project_id = "hhshfskglojdkdsuqugn"

[functions.pluggy-webhook]
verify_jwt = false

[functions.create-connect-token]
verify_jwt = true

[functions.sync-transactions]
verify_jwt = true

[functions.transactions-api]
verify_jwt = false