# supabase/config.toml
project_id = "hhshfskglojdkdsuqugn"

[functions.pluggy-webhook]
verify_jwt = false

[functions.create-connect-token]
verify_jwt = true

[functions.sync-transactions]
verify_jwt = true

[functions.transactions-api]
verify_jwt = false # Mantém false pois usa API key

# --- ADICIONAR NOVA FUNÇÃO ---
[functions.disconnect-bank]
verify_jwt = true # Requer autenticação do usuário